// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld2.proto

package io.grpc.examples.helloworld2;

/**
 * Protobuf type {@code helloworld.Role}
 */
public  final class Role extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.Role)
    RoleOrBuilder {
  // Use Role.newBuilder() to construct.
  private Role(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Role() {
    rolename_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Role(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              rolename_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            rolename_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        rolename_ = rolename_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.examples.helloworld2.HelloWorldProto2.internal_static_helloworld_Role_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.examples.helloworld2.HelloWorldProto2.internal_static_helloworld_Role_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.examples.helloworld2.Role.class, io.grpc.examples.helloworld2.Role.Builder.class);
  }

  public static final int ROLENAME_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList rolename_;
  /**
   * <code>repeated string rolename = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getRolenameList() {
    return rolename_;
  }
  /**
   * <code>repeated string rolename = 1;</code>
   */
  public int getRolenameCount() {
    return rolename_.size();
  }
  /**
   * <code>repeated string rolename = 1;</code>
   */
  public java.lang.String getRolename(int index) {
    return rolename_.get(index);
  }
  /**
   * <code>repeated string rolename = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRolenameBytes(int index) {
    return rolename_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rolename_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rolename_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < rolename_.size(); i++) {
        dataSize += computeStringSizeNoTag(rolename_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRolenameList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.examples.helloworld2.Role)) {
      return super.equals(obj);
    }
    io.grpc.examples.helloworld2.Role other = (io.grpc.examples.helloworld2.Role) obj;

    boolean result = true;
    result = result && getRolenameList()
        .equals(other.getRolenameList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRolenameCount() > 0) {
      hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getRolenameList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.examples.helloworld2.Role parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.helloworld2.Role parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.examples.helloworld2.Role parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.helloworld2.Role parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.examples.helloworld2.Role prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.Role}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.Role)
      io.grpc.examples.helloworld2.RoleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.helloworld2.HelloWorldProto2.internal_static_helloworld_Role_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.helloworld2.HelloWorldProto2.internal_static_helloworld_Role_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.helloworld2.Role.class, io.grpc.examples.helloworld2.Role.Builder.class);
    }

    // Construct using io.grpc.examples.helloworld2.Role.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      rolename_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.examples.helloworld2.HelloWorldProto2.internal_static_helloworld_Role_descriptor;
    }

    public io.grpc.examples.helloworld2.Role getDefaultInstanceForType() {
      return io.grpc.examples.helloworld2.Role.getDefaultInstance();
    }

    public io.grpc.examples.helloworld2.Role build() {
      io.grpc.examples.helloworld2.Role result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.examples.helloworld2.Role buildPartial() {
      io.grpc.examples.helloworld2.Role result = new io.grpc.examples.helloworld2.Role(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        rolename_ = rolename_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.rolename_ = rolename_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.examples.helloworld2.Role) {
        return mergeFrom((io.grpc.examples.helloworld2.Role)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.examples.helloworld2.Role other) {
      if (other == io.grpc.examples.helloworld2.Role.getDefaultInstance()) return this;
      if (!other.rolename_.isEmpty()) {
        if (rolename_.isEmpty()) {
          rolename_ = other.rolename_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRolenameIsMutable();
          rolename_.addAll(other.rolename_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.examples.helloworld2.Role parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.examples.helloworld2.Role) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList rolename_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRolenameIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        rolename_ = new com.google.protobuf.LazyStringArrayList(rolename_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRolenameList() {
      return rolename_.getUnmodifiableView();
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public int getRolenameCount() {
      return rolename_.size();
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public java.lang.String getRolename(int index) {
      return rolename_.get(index);
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRolenameBytes(int index) {
      return rolename_.getByteString(index);
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public Builder setRolename(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRolenameIsMutable();
      rolename_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public Builder addRolename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRolenameIsMutable();
      rolename_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public Builder addAllRolename(
        java.lang.Iterable<java.lang.String> values) {
      ensureRolenameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rolename_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public Builder clearRolename() {
      rolename_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rolename = 1;</code>
     */
    public Builder addRolenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRolenameIsMutable();
      rolename_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:helloworld.Role)
  }

  // @@protoc_insertion_point(class_scope:helloworld.Role)
  private static final io.grpc.examples.helloworld2.Role DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.examples.helloworld2.Role();
  }

  public static io.grpc.examples.helloworld2.Role getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Role>
      PARSER = new com.google.protobuf.AbstractParser<Role>() {
    public Role parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Role(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Role> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Role> getParserForType() {
    return PARSER;
  }

  public io.grpc.examples.helloworld2.Role getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

