// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld2.proto

package io.grpc.examples.helloworld2;

public interface RoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.Role)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string rolename = 1;</code>
   */
  java.util.List<java.lang.String>
      getRolenameList();
  /**
   * <code>repeated string rolename = 1;</code>
   */
  int getRolenameCount();
  /**
   * <code>repeated string rolename = 1;</code>
   */
  java.lang.String getRolename(int index);
  /**
   * <code>repeated string rolename = 1;</code>
   */
  com.google.protobuf.ByteString
      getRolenameBytes(int index);
}
