// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maptest1.proto

package io.grpc.examples.maptest1;

public interface MapRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lliuruichao.maptest1.MapRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
