// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maptest1.proto

package io.grpc.examples.maptest1;

public final class MapTestProto {
  private MapTestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lliuruichao_maptest1_MapRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lliuruichao_maptest1_MapRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lliuruichao_maptest1_MapReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lliuruichao_maptest1_MapReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lliuruichao_maptest1_MapReply_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lliuruichao_maptest1_MapReply_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016maptest1.proto\022\030com.lliuruichao.maptes" +
      "t1\"\032\n\nMapRequest\022\014\n\004name\030\001 \001(\t\"p\n\010MapRep" +
      "ly\0228\n\003map\030\001 \003(\0132+.com.lliuruichao.maptes" +
      "t1.MapReply.MapEntry\032*\n\010MapEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012i\n\017MapTestServi" +
      "ce1\022V\n\010getRoles\022$.com.lliuruichao.maptes" +
      "t1.MapRequest\032\".com.lliuruichao.maptest1" +
      ".MapReply\"\000B1\n\031io.grpc.examples.maptest1" +
      "B\014MapTestProtoP\001\242\002\003LRCb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lliuruichao_maptest1_MapRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lliuruichao_maptest1_MapRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lliuruichao_maptest1_MapRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_lliuruichao_maptest1_MapReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lliuruichao_maptest1_MapReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lliuruichao_maptest1_MapReply_descriptor,
        new java.lang.String[] { "Map", });
    internal_static_com_lliuruichao_maptest1_MapReply_MapEntry_descriptor =
      internal_static_com_lliuruichao_maptest1_MapReply_descriptor.getNestedTypes().get(0);
    internal_static_com_lliuruichao_maptest1_MapReply_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lliuruichao_maptest1_MapReply_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
